### ISSUE TITLE
environment in docker-compose not working

### ISSUE THREAD

**Issue by sjoerd222888** [armswarm/postgres#2]
My docker-compose.yml contains the following:

```
  postgres:
    image: armswarm/postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: password
    ports:
      - 5432
```
The environment variables seem to have no effect. It works with the default/official [postgres](https://hub.docker.com/_/postgres/) docker image but not with your image. Is there a reason for this? How can I achieve the same with your image?

Thanks.
